services:
  db:
    image: mysql:8.0
    container_name: wimy-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fridge_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wimy_mysql_data:/var/lib/mysql
    networks:
      - wimy-network

  app:
    build: ./backend             # . 에서 ./backend 로 수정
    container_name: wimy-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fridge_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - wimy-network

  frontend:
    build: ./frontend            # . 에서 ./frontend 로 수정
    container_name: wimy-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app          # 상대 경로가 ./frontend로 변경됨
      - /app/node_modules
    depends_on:
      - app
    networks:
      - wimy-network

networks:
  wimy-network:
    driver: bridge